# Generated by Django 3.2.3 on 2021-06-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/%Y/%m/%d'),
        ),
    ]
