# Generated by Django 3.2.3 on 2021-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d', verbose_name='Imagen de perfil'),
        ),
    ]
