# Generated by Django 3.2.3 on 2021-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_user_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_user',
        ),
        migrations.AddField(
            model_name='user',
            name='numcelular',
            field=models.BigIntegerField(blank=True, db_column='numero Celular', null=True, verbose_name='Celular'),
        ),
    ]
