# Generated by Django 3.2.3 on 2021-06-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210623_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numcelular',
            field=models.BigIntegerField(db_column='numero Celular', null=True, verbose_name='Celular'),
        ),
    ]
