# Generated by Django 3.2.3 on 2021-07-01 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_user_numcelular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numcelular',
            field=models.CharField(db_column='numero Celular', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Celular'),
        ),
    ]
