# Generated by Django 3.2.1 on 2021-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bicicletas',
            fields=[
                ('idbicicletas', models.AutoField(db_column='idBicicletas', primary_key=True, serialize=False)),
                ('color', models.CharField(db_column='Color', max_length=50)),
                ('material', models.TextField(db_column='Material')),
                ('precioalquiler', models.DecimalField(db_column='PrecioAlquiler', decimal_places=3, max_digits=6)),
                ('foto', models.CharField(db_column='Foto', max_length=50)),
            ],
            options={
                'db_table': 'bicicletas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idcatalogo', models.AutoField(db_column='idCatalogo', primary_key=True, serialize=False)),
                ('fechahorasubida', models.DateTimeField(db_column='fechaHoraSubida')),
            ],
            options={
                'db_table': 'catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idmodelo', models.AutoField(db_column='idModelo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(db_column='idContrato', primary_key=True, serialize=False)),
                ('cantidadbicicletas', models.IntegerField(db_column='CantidadBicicletas')),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafin', models.DateField(db_column='FechaFin')),
                ('tiempo', models.TimeField(db_column='Tiempo')),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=100)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idmodulo', models.AutoField(db_column='idModulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fechapago', models.DateTimeField(db_column='FechaPago')),
                ('totalalquiler', models.DecimalField(db_column='TotalAlquiler', decimal_places=3, max_digits=6)),
                ('fechamora', models.DateTimeField(blank=True, db_column='FechaMora', null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfilusuario',
            fields=[
                ('idroles', models.AutoField(db_column='idRoles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcionrol', models.TextField(blank=True, db_column='descripcionRol', null=True)),
            ],
            options={
                'db_table': 'perfilusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('numidentificacion', models.BigIntegerField(db_column='NumIdentificacion')),
                ('numcelular', models.BigIntegerField(db_column='NumCelular')),
                ('numtelefono', models.BigIntegerField(blank=True, db_column='NumTelefono', null=True)),
                ('correoelectronico', models.CharField(db_column='CorreoElectronico', max_length=45)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('idprivilegios', models.AutoField(db_column='idPrivilegios', primary_key=True, serialize=False)),
                ('privilegio', models.IntegerField()),
            ],
            options={
                'db_table': 'privilegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(db_column='idReserva', primary_key=True, serialize=False)),
                ('disponibleen', models.TimeField(blank=True, db_column='DisponibleEn', null=True)),
                ('disponible', models.CharField(db_column='Disponible', max_length=2)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiempoprestamo',
            fields=[
                ('idtiempodisponibilidad', models.IntegerField(db_column='idTiempoDisponibilidad', primary_key=True, serialize=False)),
                ('tiempoinicio', models.CharField(blank=True, db_column='tiempoInicio', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tiempoprestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('idtipocontrato', models.IntegerField(db_column='idTipocontrato', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipocontrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopersona',
            fields=[
                ('idtipopersona', models.AutoField(db_column='idtipoPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=55)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipopersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
