# Generated by Django 3.2.5 on 2021-07-11 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idcatalogo', models.AutoField(db_column='idCatalogo', primary_key=True, serialize=False)),
                ('fechahorasubida', models.DateTimeField(db_column='fechaHoraSubida')),
            ],
            options={
                'verbose_name_plural': 'Catalogo',
                'db_table': 'catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idmodelo', models.AutoField(db_column='idModelo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(db_column='idContrato', primary_key=True, serialize=False)),
                ('cantidadbicicletas', models.IntegerField(db_column='CantidadBicicletas')),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafin', models.DateField(db_column='FechaFin')),
                ('tiempo', models.TimeField(db_column='Tiempo')),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotoPerfiluser',
            fields=[
                ('idfotouser', models.AutoField(db_column='idfotoUser', primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Foto perfil Usuario',
                'db_table': 'foto_perfiluser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialbicicletas',
            fields=[
                ('idmaterialbicicletas', models.AutoField(db_column='idMaterialBicicletas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Material Bicicletas',
                'db_table': 'materialbicicletas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fechapago', models.DateTimeField(db_column='FechaPago')),
                ('totalalquiler', models.DecimalField(db_column='TotalAlquiler', decimal_places=3, max_digits=6)),
                ('fechamora', models.DateTimeField(blank=True, db_column='FechaMora', null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfilusuario',
            fields=[
                ('idroles', models.AutoField(db_column='idRoles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcionrol', models.TextField(blank=True, db_column='descripcionRol', null=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil Usuario',
                'db_table': 'perfilusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('numidentificacion', models.BigIntegerField(db_column='NumIdentificacion')),
                ('numcelular', models.BigIntegerField(db_column='NumCelular')),
                ('numtelefono', models.BigIntegerField(blank=True, db_column='NumTelefono', null=True)),
                ('correoelectronico', models.CharField(db_column='CorreoElectronico', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Persona',
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('idprivilegios', models.AutoField(db_column='idPrivilegios', primary_key=True, serialize=False)),
                ('privilegio', models.IntegerField()),
            ],
            options={
                'db_table': 'privilegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(db_column='idReserva', primary_key=True, serialize=False)),
                ('disponibleen', models.TimeField(blank=True, db_column='DisponibleEn', null=True)),
                ('disponible', models.CharField(db_column='Disponible', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Reserva',
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiempoprestamo',
            fields=[
                ('idtiempodisponibilidad', models.IntegerField(db_column='idTiempoDisponibilidad', primary_key=True, serialize=False)),
                ('tiempoinicio', models.CharField(blank=True, db_column='tiempoInicio', max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tiempo Prestamo',
                'db_table': 'tiempoprestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('idtipocontrato', models.IntegerField(db_column='idTipocontrato', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipocontrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.BigIntegerField(blank=True, db_column='Telefono', null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=50, null=True)),
                ('biografia', models.TextField(blank=True, db_column='Biografia', max_length=150, null=True)),
                ('image_portada', models.ImageField(blank=True, null=True, upload_to='user/banner/%Y/%m/%d', verbose_name='Imagen de portada')),
                ('image_user', models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d', verbose_name='Imagen de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='MiBicicleta',
            fields=[
                ('idmibicicleta', models.BigAutoField(db_column='idmibicicleta', primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(db_column='Disponible', default=True)),
                ('marca', models.CharField(db_column='Marca', default=None, max_length=45)),
                ('color', models.CharField(db_column='Color', default=None, max_length=50)),
                ('timestamp', models.DateTimeField(db_column='Fecha de subida', default=django.utils.timezone.now)),
                ('precioalquiler', models.DecimalField(db_column='PrecioAlquiler', decimal_places=3, default=None, max_digits=6, verbose_name='Precio Alquiler')),
                ('valortiempohoras', models.IntegerField(blank=True, db_column='Horas de alquiler', default=0, null=True)),
                ('valortiempomin', models.IntegerField(blank=True, db_column='Minutos de alquiler', default=0, null=True)),
                ('descripcionbici', models.TextField(blank=True, db_column='DescripcionBici', default=None, max_length=150, null=True)),
                ('foto', models.ImageField(db_column='Foto', null=True, upload_to='')),
                ('categoria', models.ForeignKey(db_column='Categoria', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoria')),
                ('material', models.ForeignKey(db_column='Material', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.materialbicicletas')),
                ('user', models.ForeignKey(db_column='Propietario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miBici', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bicicletas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
