# Generated by Django 3.2.3 on 2021-07-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210711_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='Obsrvaciones', max_length=1000, null=True)),
            ],
        ),
    ]
