# Generated by Django 3.2.3 on 2021-06-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_auto_20210525_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicicletas',
            options={'managed': False, 'verbose_name_plural': 'Bicicleta'},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False, 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False, 'verbose_name_plural': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='fotoperfiluser',
            options={'managed': False, 'verbose_name_plural': 'Foto perfil Usuario'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'managed': False, 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'managed': False, 'verbose_name_plural': 'Perfil Usuario'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False, 'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False, 'verbose_name_plural': 'Reserva'},
        ),
        migrations.AlterModelOptions(
            name='tiempoprestamo',
            options={'managed': False, 'verbose_name_plural': 'Tiempo Prestamo'},
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
