# Generated by Django 3.2.3 on 2021-08-02 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210802_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, db_column='Biografia', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 8, 4, 15, 34, 24, 821111)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 8, 2, 15, 34, 24, 821111)),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(blank=True, db_column='Telefono', null=True),
        ),
    ]
