# Generated by Django 3.2.3 on 2021-06-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210611_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
