# Generated by Django 3.2.3 on 2021-07-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_observaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observaciones',
        ),
    ]
