# Generated by Django 3.2.3 on 2021-08-16 14:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210810_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nombres y Apellidos', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=120)),
                ('mensaje', models.TextField(db_column='Mensaje', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 8, 18, 9, 52, 56, 214325)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mibicicleta',
            name='descripcionbici',
            field=models.TextField(blank=True, db_column='DescripcionBici', default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ0-9\\s]{1,40}$', 'La descripcion de tu Bici no puede contener caracteres especiales')]),
        ),
    ]
