# Generated by Django 3.2.3 on 2021-06-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialbicicletas',
            fields=[
                ('idmaterialbicicletas', models.AutoField(db_column='idMaterialBicicletas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'materialbicicletas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bicicletas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fotoperfiluser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tiempoprestamo',
            options={'managed': False},
        ),
    ]
