# Generated by Django 3.2.3 on 2021-06-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20210613_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicicletas',
            options={'managed': False, 'verbose_name_plural': 'Bicicleta'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='materialbicicletas',
            options={'managed': False, 'verbose_name_plural': 'Material Bicicletas'},
        ),
        migrations.AlterModelTable(
            name='materialbicicletas',
            table='Material Bicicletas',
        ),
    ]
