# Generated by Django 3.2.3 on 2021-07-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_contratobicicleta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratoBicicleta',
        ),
    ]
