# Generated by Django 3.2.3 on 2021-08-17 04:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210816_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='datetimemsg',
            field=models.DateTimeField(db_column='Fecha del mensaje', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 8, 18, 23, 5, 4, 638551)),
        ),
    ]
