# Generated by Django 3.2.3 on 2021-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210614_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbicicletas',
            options={'managed': False, 'verbose_name_plural': 'materialbicicletas'},
        ),
        migrations.AlterModelTable(
            name='materialbicicletas',
            table='materialbicicletas',
        ),
    ]
