# Generated by Django 3.2.3 on 2021-06-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20210614_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicicletas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='materialbicicletas',
            options={'managed': False},
        ),
    ]
