# Generated by Django 3.2.3 on 2021-07-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0007_contratobicicleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratobicicleta',
            name='usuario',
            field=models.ForeignKey(db_column='Arrendatario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bicicleta', to=settings.AUTH_USER_MODEL),
        ),
    ]
