# Generated by Django 3.2.3 on 2021-07-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_contratobicicleta_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
