# Generated by Django 3.2.3 on 2021-06-16 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0008_auto_20210616_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiBicicleta',
            fields=[
                ('idmibicicleta', models.AutoField(db_column='idmibicicleta', default=None, primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='Marca', default=None, max_length=45)),
                ('color', models.CharField(db_column='Color', default=None, max_length=50)),
                ('material', models.TextField(db_column='Material', default=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('precioalquiler', models.DecimalField(db_column='PrecioAlquiler', decimal_places=3, default=None, max_digits=6, verbose_name='Precio Alquiler')),
                ('foto', models.ImageField(blank='True', db_column='Foto', null=True, upload_to='')),
                ('categoria', models.ForeignKey(db_column='Categoria', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoria')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='myPost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MyBicicleta',
                'ordering': ['-timestamp'],
            },
        ),
    ]
