# Generated by Django 3.2.3 on 2021-07-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_delete_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratobicicleta',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='bicicleta',
            field=models.ForeignKey(db_column='Bicicleta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.mibicicleta'),
        ),
    ]
