# Generated by Django 3.2.3 on 2021-06-17 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0009_mibicicleta_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False, 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False, 'verbose_name_plural': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='fotoperfiluser',
            options={'managed': False, 'verbose_name_plural': 'Foto perfil Usuario'},
        ),
        migrations.AlterModelOptions(
            name='materialbicicletas',
            options={'managed': False, 'verbose_name_plural': 'Material'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'managed': False, 'verbose_name_plural': 'Foto perfil Usuario'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'managed': False, 'verbose_name_plural': 'Perfil Usuario'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False, 'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False, 'verbose_name_plural': 'Reserva'},
        ),
        migrations.AlterModelOptions(
            name='tiempoprestamo',
            options={'managed': False, 'verbose_name_plural': 'Tiempo Prestamo'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen_portada',
            field=models.ImageField(blank='True', db_column='Imagen Portada', default='bannerdefault.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mibicicleta',
            name='material',
            field=models.ForeignKey(db_column='Material', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.materialbicicletas'),
        ),
        migrations.AlterField(
            model_name='mibicicleta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miBici', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pagos',
            table='foto_perfiluser',
        ),
    ]
