# Generated by Django 3.2.3 on 2021-07-26 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210721_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratobicicleta',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='contratobicicleta',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contratobicicleta',
            name='horafin',
            field=models.IntegerField(db_column='Hora fin', default=None),
        ),
        migrations.AddField(
            model_name='contratobicicleta',
            name='horainicio',
            field=models.TimeField(db_column='Hora inicio', default=None),
        ),
        migrations.AddField(
            model_name='contratobicicleta',
            name='numeroDocumento',
            field=models.BigIntegerField(db_column='Numero Documento', default=None),
        ),
        migrations.AddField(
            model_name='contratobicicleta',
            name='tipodocumento',
            field=models.IntegerField(choices=[[0, 'Cédula de Ciudadania'], [1, 'Carnet de Extranjeria']], db_column='Tipo de Documento', default=0),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 9, 12, 9, 34, 54, 42303)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 26, 9, 34, 54, 42303)),
        ),
    ]
