# Generated by Django 3.2.3 on 2021-08-18 02:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_contratobicicleta_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='datetimemsg',
            field=models.DateTimeField(db_column='Fecha del mensaje', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(db_column='Mensaje', max_length=500, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZÀ-ÿ\\s]{1,200}$', 'Este campo no acepta caracteres especiales')]),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 8, 19, 21, 57, 11, 447830)),
        ),
    ]
