# Generated by Django 3.2.3 on 2021-06-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210617_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d', verbose_name='Imagen de perfil'),
        ),
    ]
