# Generated by Django 3.2.3 on 2021-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_perfil_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen_portada',
        ),
        migrations.AddField(
            model_name='perfil',
            name='image_portada',
            field=models.ImageField(blank=True, null=True, upload_to='user/banner/%Y/%m/%d', verbose_name='Imagen de portada'),
        ),
    ]
