# Generated by Django 3.2.3 on 2021-07-26 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20210726_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratobicicleta',
            name='estado',
            field=models.BooleanField(db_column='estado', default=True),
        ),
        migrations.AddField(
            model_name='mibicicleta',
            name='estado',
            field=models.BooleanField(db_column='estado', default=True),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 9, 12, 9, 36, 37, 570224)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 26, 9, 36, 37, 570224)),
        ),
    ]
