# Generated by Django 3.2.3 on 2021-07-26 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20210726_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratobicicleta',
            old_name='numeroDocumento',
            new_name='numerodocumento',
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 9, 12, 9, 42, 8, 853173)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 26, 9, 42, 8, 853173)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='tipocontrato',
            field=models.ForeignKey(db_column='Tipocontrato', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tipocontrato'),
        ),
    ]
