# Generated by Django 3.2.3 on 2021-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_mibicicleta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='idmibicicleta',
            field=models.BigAutoField(db_column='idmibicicleta', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
