# Generated by Django 3.2.3 on 2021-07-26 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20210726_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 9, 12, 9, 50, 12, 543838)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 26, 9, 50, 12, 543838)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='horafin',
            field=models.TimeField(db_column='Hora fin', default=None),
        ),
    ]
