# Generated by Django 3.2.3 on 2021-06-24 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_alter_mibicicleta_idmibicicleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mibicicleta',
            name='descripcionbici',
            field=models.TextField(db_column='DescripcionBici', default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Texto muy corto', regex='^.{10}$')]),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Biografia',
            field=models.TextField(db_column='Biografia', max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Texto muy corto', regex='^.{10}$')]),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Direccion',
            field=models.CharField(db_column='Direccion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(blank=True, db_column='Telefono', null=True),
        ),
    ]
