# Generated by Django 3.2.3 on 2021-06-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20210623_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Direccion',
            new_name='direccion',
        ),
    ]
