# Generated by Django 3.2.3 on 2021-06-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20210623_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'managed': False, 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelTable(
            name='pagos',
            table='Pagos',
        ),
    ]
