# Generated by Django 3.2.3 on 2021-07-28 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210727_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False, 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 7, 29, 22, 8, 1, 45344)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 27, 22, 8, 1, 45344)),
        ),
    ]
