# Generated by Django 3.2.3 on 2021-06-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210623_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bicicletas',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False, 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='materialbicicletas',
            options={'managed': False, 'verbose_name_plural': 'Material Bicicletas'},
        ),
        migrations.AlterModelOptions(
            name='mibicicleta',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Bicicletas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='Contrato',
        ),
    ]
