# Generated by Django 3.2.3 on 2021-07-28 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20210727_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 7, 29, 22, 22, 2, 705484)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 27, 22, 22, 2, 705484)),
        ),
        migrations.CreateModel(
            name='CatalogoBicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nombre', max_length=50)),
                ('bicicleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.mibicicleta')),
            ],
            options={
                'verbose_name_plural': 'Catalogo',
            },
        ),
    ]
