# Generated by Django 3.2.3 on 2021-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20210623_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='descripcionbici',
            field=models.TextField(blank=True, db_column='DescripcionBici', default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, db_column='Biografia', max_length=150, null=True),
        ),
    ]
