# Generated by Django 3.2.3 on 2021-07-28 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20210727_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 7, 30, 11, 10, 36, 856963)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 28, 11, 10, 36, 856963)),
        ),
    ]
