# Generated by Django 3.2.3 on 2021-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20210630_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=50, null=True),
        ),
    ]
