# Generated by Django 3.2.3 on 2021-07-28 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20210728_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogobicicleta',
            name='bicicleta',
        ),
        migrations.AddField(
            model_name='catalogobicicleta',
            name='bicicletacat',
            field=models.ForeignKey(db_column='Bicicleta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.mibicicleta'),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechafin',
            field=models.DateTimeField(db_column='fechafin', default=datetime.datetime(2021, 7, 30, 11, 48, 34, 375230)),
        ),
        migrations.AlterField(
            model_name='contratobicicleta',
            name='fechainicio',
            field=models.DateTimeField(db_column='Fecha Inicio Contrato', default=datetime.datetime(2021, 7, 28, 11, 48, 34, 375230)),
        ),
    ]
