# Generated by Django 3.2.3 on 2021-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_alter_perfil_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mibicicleta',
            name='valotiempoalquiler',
            field=models.TimeField(blank=True, default=None, verbose_name='Conversation Time'),
        ),
    ]
