# Generated by Django 3.2.3 on 2021-07-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_mibicicleta_valotiempoalquiler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mibicicleta',
            old_name='valotiempoalquiler',
            new_name='valortiempoalquiler',
        ),
    ]
