# Generated by Django 3.2.3 on 2021-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_auto_20210701_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='foto',
            field=models.ImageField(db_column='Foto', null=True, upload_to=''),
        ),
    ]
