# Generated by Django 3.2.3 on 2021-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_alter_mibicicleta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='valortiempohoras',
            field=models.IntegerField(blank=True, db_column='Horas de alquiler', default=23, null=True),
        ),
        migrations.AlterField(
            model_name='mibicicleta',
            name='valortiempomin',
            field=models.IntegerField(blank=True, db_column='Minutos de alquiler', default=0, null=True),
        ),
    ]
