# Generated by Django 3.2.3 on 2021-07-01 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_auto_20210701_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(blank=True, db_column='Telefono', max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
