# Generated by Django 3.2.3 on 2021-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_alter_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='valortiempohoras',
            field=models.IntegerField(blank=True, db_column='Horas de alquiler', default=0, null=True),
        ),
    ]
