# Generated by Django 3.2.3 on 2021-07-01 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_alter_mibicicleta_valortiempohoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibicicleta',
            name='timestamp',
            field=models.DateTimeField(db_column='Fecha de subida', default=django.utils.timezone.now),
        ),
    ]
