# Generated by Django 3.2.3 on 2021-07-01 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_alter_mibicicleta_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(blank=True, db_column='Telefono', null=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
